# Generic labels
- name: bug
  description: Something isn't working
  color: d73a4a
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: enhancement
  description: New feature or request
  color: a2eeef
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: question
  description: Further information is requested
  color: d876e3
- name: wontfix
  description: This will not be worked on
  color: ffffff
- name: blocked
  description: This issue is blocked by some other work
  color: e0af74
- name: critical
  description: This issue needs critical attention
  color: B60205
- name: infra
  description: Infra, devops, CI and related tasks
  color: 277196
- name: milestone
  description: Tracks a subteam milestone
  color: 1CC0B0
- name: epic
  description: Tracks a yearly team epic (only for cowprotocol/pm repo)
  color: 07544B
- name: test
  description: Issue related to the test suite with no expected consequence to production code
  color: 277196
- name: release-notes
  description: Issue/PR needs to be evaluated for inclusion in release notes highlights or upgrade instructions
  color: fb3c99
- name: oncall
  description: Issue/PR for consideration during oncall rotation
  color: ffbf00
- name: track:frontend-maintenance
  description: frontend maintenance track
  color: 6BEB00
- name: track:services-maintenance
  description: services maintenance track (Protocol)
  color: 40F9F0
- name: track:maintenance
  description: 218bff

## Team labels
- name: team:backend
  description: Issues / PRs scoped to backend
  color: 7779d0
- name: team:contracts
  description: Issues / PRs scoped to contracts
  color: 591248
- name: team:frontend
  description: Issues / PRs scoped to frontend
  color: bfdadc
- name: team:marketing
  description: Issues / PRs scoped to marketing
  color: 5319e7
- name: team:solvers
  description: Issues / PRs scoped to solvers
  color: 4da6ab

## [Milestone] External Contributor Friendly
- name: "E:1.1: Conditional Order Templates"
  description: https://github.com/cowprotocol/pm/issues/1
  color: FEF445
- name: "E:1.2: Watch Tower Service"
  description: https://github.com/cowprotocol/pm/issues/8
  color: 0052cc
- name: "E:1.3: Merkle Tree Support"
  description: https://github.com/cowprotocol/pm/issues/9
  color: 6D5261
- name: "E:2.1: Documentation and Tutorials"
  description: https://github.com/cowprotocol/pm/issues/10
  color: 24B684

# [Milestone] Complexity Reduction
- name: "E:3.1 Driver Colocation"
  description: See https://github.com/cowprotocol/pm/issues/14 for details
  color: fef2c0
- name: "E:3.2 Verified Quotes"
  description: See https://github.com/cowprotocol/pm/issues/15 for details
  color: bfd4f2
- name: "E:3.3 Factor out ETHFlow"
  description: See https://github.com/cowprotocol/pm/issues/20 for details
  color: 2a2f52
- name: "E:3.4 Self-documenting Rest APIs"
  description: See https://github.com/cowprotocol/pm/issues/23 for details
  color: 95d888

# [Milestone] Sustainability
- name: "E:4.1 Quote adjustment for solvers"
  description: See https://github.com/cowprotocol/pm/issues/26 for details
  color: 54d412
- name: "E:4.2 Protocol Fee Implementation"
  description: See https://github.com/cowprotocol/pm/issues/29 for details
  color: 99E52F

# [Milestone] Contracts Evolution
- name: "E:5.1 Standardise contracts repository"
  description: See https://github.com/cowprotocol/pm/issues/31 for details
  color: 0052cc
- name: "E:5.2 Contracts migrations"
  description: See https://github.com/cowprotocol/pm/issues/32 for details
  color: bfd4f2

# [Milestone] Faster Execution Speed
- name: "E:6.1 One auction per block"
  description: See https://github.com/cowprotocol/pm/issues/35 for details
  color: f9d0c4

# [Milestone] Solver Driver Colocation
- name: "E:7.1 Ext. solvers operating driver"
