name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml
jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/action-label-syncer@0.2.0
        with:
          manifest: .github/labels.yml
          repository: |
            cowprotocol/pm
            cowprotocol/tenderly-watch-tower
            cowprotocol/docs
            cowprotocol/docs-v2
            cowprotocol/services
            cowprotocol/infrastructure
            cowprotocol/autodeploy-action
            cowprotocol/dappnodepackage-cow-watch-tower
            cowprotocol/snapshot-settings
            cowprotocol/clogs
            cowprotocol/composable-cow
            cowprotocol/composable-dao
            cowprotocol/contracts
            cowprotocol/ethflowcontract
            cowprotocol/hooks-trampoline
            cowprotocol/loot
            cowprotocol/token
            cowprotocol/token-imbalances
            cowprotocol/solver-rewards
            cowprotocol/prefect
            cowprotocol/dune-queries
            cowprotocol/circuit-breaker
            cowprotocol/tenderly-alerts
          token: ${{ secrets.SYNC_LABELS }}
          prune: true
